### ISSUE TITLE
Any plan to release?

### ISSUE THREAD

**Issue by scorpioliu** [Haian-Jin/Neural_Gaffer#1] opened 2024-06-14 02:41 UTC
the result is GREAT!

**Comment by Haian-Jin** [comment] 2024-06-14 05:47
Hi, thanks for your interests.

The releasing date will depend on the review results. If everything goes well, I will release all code and model checkpoints as soon as possible.

**Comment by dreamingtulpa** [comment] 2024-06-14 12:52
Thanks Haian. Sorry to bother. But could you shine a light on why the release depends on review results?

I see a lot of papers getting published without code to reproduce the results.

Simply wondering what's the thought process behind this.

**Comment by Haian-Jin** [comment] 2024-06-14 18:10
> Thanks Haian. Sorry to bother. But could you shine a light on why the release depends on review results?
> 
> I see a lot of papers getting published without code to reproduce the results.
> 
> Simply wondering what's the thought process behind this.

First,  I think it's it is quite common in the research community to release code based on the review results or after a paper has been accepted. 

Second, I have promised to release all code for this project in the future, and I have always released all code for all of my past publications. I'm not sure why you mentioned that some papers did not provide code to reproduce their results even after publication.

**Comment by jimmeguy1967** [comment] 2024-06-14 23:16
that's great! Will this work for comfyui?

**Comment by dreamingtulpa** [comment] 2024-06-17 07:17
> First, I think it's it is quite common in the research community to release code based on the review results or after a paper has been accepted.

How come? I would like to understand the thought process / reasons behind this. Why not release the code before?

> Second, I have promised to release all code for this project in the future, and I have always released all code for all of my past publications. I'm not sure why you mentioned that some papers did not provide code to reproduce their results even after publication.

I'm not saying you won't release your code, I'm just trying to understand the reason code doesn't get released with a paper being published ;)

I curate a lot of CV papers each week for aiartweekly.com, and often code doesn't get released, even after a few months. Which causes a lot of frustration and mistrust in the open-source community. I feel there is a misunderstanding between the research and OS community in this regard, I'm trying to clear that up. Any insights are appreciated.

**Comment by WonsukYang** [comment] 2024-08-26 05:27
Hey @Haian-Jin Thank you for the amazing work!
A quick question: is your checkpoint based on SDXL or SD 1.5?

**Closed** 2024-11-20 19:06 UTC
